event_manager/event_manager/urls.py
"""
PROJEKT URLS

admin2 token: b924fca2063f615acdc17759ee464e814adda815
"""

from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from rest_framework.authtoken.views import obtain_auth_token
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("api/token", obtain_auth_token, name="token"),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # api/events/categories
    path("api/events/", include("events.api.urls")),
    # path("api/", include("pages.api.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("pages.urls")),  # http://127.0.0.1:8000
    path("admin/", admin.site.urls),  # http://127.0.0.1:8000/admin
    path("events/", include("events.urls")),  # http://127.0.0.1:8000/events/*

    path(
        "schema/",
        SpectacularAPIView.as_view(api_version="v1"),
        name="schema",
    ),
    path(
        "docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),  # aus schema/
        name="swagger-ui",
    ),


] + debug_toolbar_urls()

event_manager/events/api/urls.py
from django.urls import path

from .views import (
    CategoryListCreateView,
    CategoryRetrieveUpdateDestroyView,
    EventListCreateView,
)

urlpatterns = [
    path("", EventListCreateView.as_view(), name="event-list-create"),
    path("category", CategoryListCreateView.as_view(), name="category-list-create"),
    path(
        "category/<int:pk>",
        CategoryRetrieveUpdateDestroyView.as_view(),
        name="category-retrieve-update-destroy",
    ),
]

event_manager/events/urls.py
"""
Events URLs

http://127.0.0.1:8000/events/hello
"""

from django.urls import path
from . import views

app_name = "events"  # immer anlegen, ist der Name der app
# events:category

urlpatterns = [
    path("hello", views.hello_world, name="hello_world"),
    path("categories", views.categories, name="categories"),
    # events/category/3
    path("category/<int:pk>", views.category, name="category"),
    # events/category
    path("category", views.category_create, name="category_create"),
    path("category/<int:pk>/update", views.category_update, name="category_update"),
    # events/
    # .as_view() immer bei klassenbasierten Views (erzeugt Einstiegs-Funktion)
    path("", views.EventListView.as_view(), name="events"),
    path("<int:pk>", views.EventDetailView.as_view(), name="event"),  # /events/3
    # /events/create
    path("create", views.EventCreateView.as_view(), name="event_create"),
    # /events/3/update
    path("<int:pk>/update", views.EventUpdateView.as_view(), name="event_update"),
    # /events/3/delete
    path("<int:pk>/delete", views.EventDeleteView.as_view(), name="event_delete"),
]

event_manager/pages/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

event_manager/events/models.py
from functools import partial
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse  # löst die URL auf
from django.core.validators import MinLengthValidator

from .validators import date_in_future, bad_word_filter


User = get_user_model()  # aktuelles User-Model


class DateMixin(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True
    )  # Beim Anlegen einmalig sdfasdf asd
    updated_at = models.DateTimeField(auto_now=True)  # beim Updaten Timestamp setzen

    class Meta:
        abstract = True


class Category(DateMixin):
    """Kategorie für einen Event."""

    class Meta:
        ordering = ["name"]  # "-name"
        verbose_name = "Kategorie"
        verbose_name_plural = "Kategorien"

    name = models.CharField(max_length=100, unique=True)  # VARCHAR 100

    # blank=True => darf im Formular leer sein
    # null=True => darf in der DB null sein (nullable)
    sub_title = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name="Untertitel",
    )
    description = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name


class Event(DateMixin):
    """Eventobjekt mit Datum und User."""

    class GroupSize(models.IntegerChoices):
        BIG = 10
        SMALL = 2

    name = models.CharField(
        max_length=100,
        unique=True,
        validators=[MinLengthValidator(3)],
    )
    sub_title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(
        null=True,
        blank=True,
        validators=[
            partial(bad_word_filter, ["evil", "blöd"]),
        ],
    )
    date = models.DateTimeField(validators=[date_in_future])
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="events",  # bob.events.all()
    )
    min_group = models.IntegerField(choices=GroupSize.choices)

    # https://docs.djangoproject.com/en/5.1/ref/models/fields/
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,  # was passiert, wenn Kategorie gelöscht wird?
        related_name="events",
    )  # Related Manager. sport.events.all()
    is_active = models.BooleanField(default=True)

    def get_related_events(self):
        """zu einem Event ähnliche Events zurückgeben."""
        related_events = Event.objects.filter(
            min_group=self.min_group, 
            category=self.category
        )
        return related_events.exclude(pk=self.pk)

    def get_absolute_url(self):
        """Das ist die Route zur Heimatseite / Detailseite."""
        return reverse("events:event", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.name

event_manager/events/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Category, Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = "__all__"
        exclude = ("author",)

        widgets = {
            "date": forms.DateInput(
                attrs={"type": "datetime-local"},
                format=("%Y-%m-%d %H:%M"),  # iso8601-format
            ),
        }

    def clean_sub_title(self):
        """Clean oder Validierung vornehmen. Rückgabewert dieser Funktion
        ist der neue Subtitle, nach Absenden des Formulars und vor Eintrag in die DB."""
        sub_title = self.cleaned_data["sub_title"]
        illegal_chars = ("*", "-")
        if isinstance(sub_title, str) and sub_title.startswith(illegal_chars):
            raise ValidationError(
                "Der Subtitle darf nicht mit illegalen Zeichen beginnen."
            )
        return sub_title

    def clean(self) -> dict:
        """Clean eigent sich für Crossfield-Validierung (feldübergreifende Validierung)."""
        super().clean()  # ruft die Feld-Validierer auf

        sub_title = self.cleaned_data["sub_title"] or ""
        name = self.cleaned_data["name"] or ""

        if "ab" in sub_title and "ab" in name:
            raise ValidationError("ab in Name und Subtitle geht nicht")

        return self.cleaned_data

    # message = forms.CharField(max_length=200, required=True)


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

event_manager/events/api/views.py
from rest_framework import generics

# from rest_framework.authentication import SessionAuthentication, TokenAuthentication
# from rest_framework.permissions import IsAuthenticated
from drf_spectacular.utils import extend_schema, OpenApiExample
from .serializers import CategorySerializer, EventSerializer
from .permissions import IsAdminuserOrReadOnly
from events.models import Category, Event


@extend_schema(description="bl ablub text")
class EventListCreateView(generics.ListCreateAPIView):
    """View zum Anlegen und Auflisten von Events."""

    queryset = Event.objects.all()
    serializer_class = EventSerializer
    permission_classes = [IsAdminuserOrReadOnly]
    # authentication_classes = [TokenAuthentication]

    def perform_create(self, serializer):
        """Den Author hinzufügen."""
        author = self.request.user
        serializer.save(author=author)


class CategoryListCreateView(generics.ListCreateAPIView):
    # da im Inline-Serializer StringRelatedField() genutzt wird,
    # ist es besser, die User-Daten gleich vorzuladen
    queryset = Category.objects.prefetch_related("events__author")
    serializer_class = CategorySerializer


class CategoryRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

event_manager/events/views.py
import logging
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpRequest, Http404
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Category, Event
from .forms import CategoryForm, EventForm

logger = logging.getLogger("django")


class IsModerator(UserPassesTestMixin):
    """Prüfen, ob User der Moderatoren-Gruppe angehört."""
    def test_func(self) -> bool:
        return self.request.user.groups.filter(name="moderatoren").exists()


class UserIsOwnerMixin(UserPassesTestMixin):
    def test_func(self) -> bool:
        """Prüfen, ob einloggter User gleich Author des Events."""
        return any(
            [
            self.request.user == self.get_object().author,
            self.request.user.is_superuser  # ist Admin
            ]
        )


class EventDeleteView(UserIsOwnerMixin, SuccessMessageMixin, DeleteView):
    """
    events/3/delete
    """

    model = Event
    success_url = reverse_lazy("events:events")
    success_message = "Event wurde erfolgreich gelöscht"
    # Modelname_confirm_delete.html


class EventUpdateView(UserIsOwnerMixin, SuccessMessageMixin, UpdateView):
    """
    /events/3/update
    """

    model = Event
    form_class = EventForm
    success_message = "Event wurde erfolgreich editiert."

    


class EventCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """Nach erfolgreicher Erstellung wird an die Addresse von
    obj.get_absolute_url() weitergeleitet (siehe events/models.py)

    /events/create
    """

    model = Event
    form_class = EventForm
    success_message = "Event wurde erfolgreich angelegt."
    # event_form.html

    def form_valid(self, form):
        """Wird aufgerufen, wenn Formular valdide."""
        # print(
        #     "message: ", form.cleaned_data["message"]
        # )  # Zugriff auf Formulardaten ohne Model
        form.instance.author = self.request.user
        logger.info("Es wurde der Author hinzugefügt.")
        return super().form_valid(form)


class EventDetailView(DetailView):
    model = Event
    # event_detail.html


class EventListView(LoginRequiredMixin, ListView):
    model = Event
    queryset = Event.objects.select_related("category", "author").all()
    # generische Name events/event_list.html
    # https://127.0.0.1:8000/events?search=eiu

    # event_detail.html

    # /events/?search=suchanfrage
    def get_queryset(self):
        suchanfrage = self.request.GET.get("search")
        if suchanfrage:
            return super().get_queryset().filter(name__contains=suchanfrage)
        return super().get_queryset()


def category_update(request, pk):
    """
    GET & POST: events/3/update
    """
    category = get_object_or_404(Category, pk=pk)
    form = CategoryForm(request.POST or None, instance=category)

    if form.is_valid():
        form.save()
        return redirect("events:categories")

    return render(
        request,
        "events/category_form.html",
        {"form": form},
    )


@login_required()
def category_create(request):
    """
    GET & POST: events/create
    """
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            return redirect("events:categories")
    else:
        form = CategoryForm()

    return render(
        request,
        "events/category_form.html",
        {"form": form},
    )


def category(request, pk):
    """
    events/category/3
    """
    # try:
    #     category = Category.objects.get(pk=pk)
    # except Category.DoesNotExist:
    #     raise Http404("Diese Category ist nicht vorhanden.")

    # shortcut für den try-except-Block
    category = get_object_or_404(Category, pk=pk)

    return render(request, "events/category.html", {"category": category})


def categories(request) -> HttpResponse:
    """
    /events/categories?x=3
    """
    categories = Category.objects.all()  # categories[0].name
    return render(
        request,
        "events/categories.html",
        {
            "categories": categories,
        },
    )


# Create your views here.
def hello_world(request: HttpRequest) -> HttpResponse:
    """
    View:
    - hat Parameter request objekt
    - gibt ein HTTP-Response-Objekt zurück
    """
    print(f"{request.method=}")
    print(f"{request.GET=}")
    print(f"{request.user=}")
    print(request.headers)
    return HttpResponse("<b>hallo</b> gfu")

event_manager/events/templates/events/categories.html
{% extends "base.html" %}

{% block title %}
Kategorieübersicht
{% endblock %}


{% block content %}
<a href="{% url 'events:category_create' %}">neue Kategorie eintragen</a>

<h1>Übersicht der Kategorien</h1>
<ul>
    {% for category in categories %}
    <li>
        <a href="{% url 'events:category' category.pk %}">{{category}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

event_manager/events/templates/events/category.html
{% extends "base.html" %}
{% load pagestags %}

{% block title %}
    {{category}}
{% endblock %}

{% block content %}
    
    
    {% comment %}
    hier kann alles reingeschrieben werden, wird nicht von der Template-Engine gerendert
    {% endcomment %}

    <a href="{% url 'events:categories' %}">zurück zur Kategorieübersicht</a><br>
    {{category}}
    <br>
    <a href="{% url 'events:category_update' category.pk %}">edit</a>

{% endblock %}

event_manager/events/templates/events/category_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Neue Kategorie eintragen
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}

<div>
<input type="button" class="btn btn-primary" value="mach nix">
<input type="submit" class="btn btn-primary" value="Formular absenden">
</div>
</form>
{% endblock %}

event_manager/events/templates/events/event_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Event löschen
{% endblock %}

{% block content %}
<p>Du willst ein Event löschen!</p>
<div class="container">
<div class="row">
    <div class="col-lg-6">

        <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Wirklich löschen?">
</div>
</div>
</div>
</form>
{% endblock %}

event_manager/events/templates/events/event_detail.html
{% extends "base.html" %}

{% block title %}
    {{object}}
{% endblock %}

{% block content %}

    <a href="{% url 'events:events' %}">zurück zur Event-Übersicht</a><br>
    {{object}}

    {% if user == object.author %}
    <p>
        <a href="{% url 'events:event_delete' object.pk %}">Event löschen</a>
    </p>
    {% endif %}

    <p>
        {{object.sub_title|default:"-"}}
    </p>

    <p>
        {{object.description|linebreaks}}
    </p>
    <p>
        {{object.date}}
    </p>

    <ul>
    {% for related in object.get_related_events %}
        <li>
            <a href="{{related.get_absolute_url}}">
            {{related}}
            </a>
        </li>
    {% endfor %}
    <ul>

{% endblock %}

event_manager/events/templates/events/event_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Neuen Event eintragen
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-lg-6">

        <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-primary" value="Formular absenden">
</div>
</div>
</div>
</form>
{% endblock %}

event_manager/events/templates/events/event_list.html
{% extends "base.html" %}

{% block title %}
Event-Übersicht
{% endblock %}


{% block content %}
<a href="{% url 'events:event_create' %}">Event hinzufügen</a><br>
<ul>
    <!-- im Template steht die Liste als object_list zur Verfügung-->

    {% if object_list %}

        {% for object in object_list %}
        <li>
            <a href="{% url 'events:event' object.pk %}">{{object}} [{{object.category}}]</a>
            (von {{object.author.username}}) 

            {% if user == object.author or user.is_superuser %}
                [<a href="{% url 'events:event_update' object.pk %}">edit</a>]
            {% endif %}

        </li>
        {% endfor %}

    {% else %}
        <li>Keine Objekte vorhanden</li>
    {% endif %}
</ul>


{% endblock %}